### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by kevinheyo** [micheleangioni/entrust#1]
"michele-angioni/entrust": "~3.0"

Problem 1
    - The requested package michele-angioni/entrust could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

"michele-angioni/entrust": "~3.0@dev"  is okay

**Comment by micheleangioni** [comment]
Thanks @kevinheyo .
However this fork has been merged back to the [original Zizaco/Entrust repo](https://github.com/Zizaco/entrust/tree/laravel-5) in the new laravel-5 branch. Please use that from now on, since this fork will be deleted in a few days.
