### ISSUE TITLE
Cannot generate the Entrust migration (for Laravel 5)

### ISSUE THREAD

**Issue by kevinheyo** [micheleangioni/entrust#2]
Firstly, I followed the instructions, add the following lines to the "config/app.php"

　　'MicheleAngioni\Entrust\EntrustServiceProvider' 
　　'Entrust' => 'MicheleAngioni\Entrust\EntrustFacade'
　
　
Second, I'v published the configuration. The console showed message of "Publishing Complete" .
　　php artisan vendor:publish
　
　
Third, some errors shown after I typed the following command:
　　php artisan entrust:migration

Tables: roles, role_user, permissions, permission_role 
A migration that creates 'roles', 'role_user', 'permissions', 'permission_role' tables will be created in app/database/migrations directory

Proceed with the migration creation? [Yes|no] Y

Creating migration...

exception 'InvalidArgumentException' with message 'View [ma_entrust.generators.migration] not found.' in D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:140

Stack trace:

#0 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(77): Illuminate\View\FileViewFinder->findInPaths('ma_entrust.gene...', Array)
#1 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\View\Factory.php(145): Illuminate\View\FileViewFinder->find('ma_entrust.gene...')
#2 D:\xampp\htdocs\Aurora\vendor\michele-angioni\entrust\src\commands\MigrationCommand.php(82): Illuminate\View\Factory->make('ma_entrust.gene...')
#3 D:\xampp\htdocs\Aurora\vendor\michele-angioni\entrust\src\commands\MigrationCommand.php(50): MicheleAngioni\Entrust\MigrationCommand->createMigration('roles', 'role_user', 'permissions', 'permission_role')
#4 [internal function]: MicheleAngioni\Entrust\MigrationCommand->fire()
#5 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#6 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\Console\Command.php(115): Illuminate\Container\Container->call(Array)
#7 D:\xampp\htdocs\Aurora\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\Console\Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 D:\xampp\htdocs\Aurora\vendor\symfony\console\Symfony\Component\Console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 D:\xampp\htdocs\Aurora\vendor\symfony\console\Symfony\Component\Console\Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(MicheleAngioni\Entrust\MigrationCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 D:\xampp\htdocs\Aurora\vendor\symfony\console\Symfony\Component\Console\Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 D:\xampp\htdocs\Aurora\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\xampp\htdocs\Aurora\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}

**Comment by TomCaserta** [comment]
Getting this error too. Hopefully a fix is posted soon! Gunna look into it now myself to see what the issue is.
